# Generated by Django 5.0.6 on 2024-07-27 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_veiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="modelos", to="core.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="modelo",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="modelos", to="core.marca"
            ),
        ),
    ]
