# Generated by Django 5.0.6 on 2024-07-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_veiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="categorias", to="core.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="modelo",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="marcas", to="core.marca"
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="cor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="veiculos", to="core.cor"
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="veiculos", to="core.modelo"
            ),
        ),
    ]
